services:
  app:
    build: .
    ports:
      - '${APP_PORT}:3000'
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo:6
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - ./data:/data/db
    env_file:
      - .env
